from __future__ import annotations

MAX_STEPS_PER_RUN: int = 10
MAX_RETRIES_PER_STEP: int = 2
MAX_AB_REPLANS_PER_RUN: int = 1
MAX_AB_FLOW_RESTARTS: int = 1

AB_DOMCONTENTLOADED_TIMEOUT_S: int = 15
AB_NETWORKIDLE_TIMEOUT_S: int = 8
AB_VALIDATION_WAIT_TIMEOUT_S: int = 8
AB_SCROLL_RETRY_COUNT: int = 3
AB_SCROLL_RETRY_PX: int = 400
AB_SCROLL_SETTLE_TIMEOUT_S: int = 1
MAX_TESTID_SEARCH_ACTIONS: int = 8
