"""Multi-language caption translation for demo subtitles.

Uses a compact phrase table for common journey templates, then falls back to
Azure OpenAI when configured (same stack as azure_subtitles).
"""

from __future__ import annotations

import json
import logging
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

logger = logging.getLogger(__name__)

SUPPORTED_LANGS = ("en", "es", "fr", "de", "pt", "ja", "hi")

# Template fragments → translations. Order matters (longer first when matching).
_PHRASES: Dict[str, Dict[str, str]] = {
    "We open the starting link and land on {x}.": {
        "es": "Abrimos el enlace inicial y llegamos a {x}.",
        "fr": "Nous ouvrons le lien de départ et arrivons sur {x}.",
        "de": "Wir öffnen den Startlink und landen auf {x}.",
        "pt": "Abrimos o link inicial e chegamos em {x}.",
        "ja": "開始リンクを開き、{x} に到着します。",
        "hi": "हम शुरुआती लिंक खोलते हैं और {x} पर पहुँचते हैं।",
    },
    "We focus on “{x}” — the next control to click.": {
        "es": "Nos centramos en “{x}”: el siguiente control a pulsar.",
        "fr": "Nous ciblons « {x} » — le prochain contrôle à cliquer.",
        "de": "Wir fokussieren „{x}“ — das nächste Steuerelement.",
        "pt": "Focamos em “{x}” — o próximo controle a clicar.",
        "ja": "次にクリックする操作「{x}」にフォーカスします。",
        "hi": "हम “{x}” पर ध्यान देते हैं — अगला क्लिक नियंत्रण।",
    },
    "Next, we click “{x}” and arrive at {y}.": {
        "es": "Luego hacemos clic en “{x}” y llegamos a {y}.",
        "fr": "Ensuite, nous cliquons sur « {x} » et arrivons sur {y}.",
        "de": "Als Nächstes klicken wir auf „{x}“ und erreichen {y}.",
        "pt": "Em seguida, clicamos em “{x}” e chegamos a {y}.",
        "ja": "次に「{x}」をクリックし、{y} に到着します。",
        "hi": "अगला, हम “{x}” पर क्लिक करते हैं और {y} पर पहुँचते हैं।",
    },
    "We click “{x}” and reach the end of the journey on {y}.": {
        "es": "Hacemos clic en “{x}” y terminamos el recorrido en {y}.",
        "fr": "Nous cliquons sur « {x} » et terminons le parcours sur {y}.",
        "de": "Wir klicken auf „{x}“ und beenden die Reise auf {y}.",
        "pt": "Clicamos em “{x}” e concluímos a jornada em {y}.",
        "ja": "「{x}」をクリックし、{y} でジャーニーを完了します。",
        "hi": "हम “{x}” पर क्लिक करते हैं और {y} पर यात्रा समाप्त करते हैं।",
    },
    "We navigate to {x} — end of the recorded path.": {
        "es": "Navegamos a {x}: fin del recorrido grabado.",
        "fr": "Nous naviguons vers {x} — fin du parcours enregistré.",
        "de": "Wir navigieren zu {x} — Ende des aufgezeichneten Pfads.",
        "pt": "Navegamos para {x} — fim do caminho gravado.",
        "ja": "{x} に移動します — 記録パスの終端です。",
        "hi": "हम {x} पर नेविगेट करते हैं — रिकॉर्डेड पथ का अंत।",
    },
    "We navigate onward to {x}.": {
        "es": "Continuamos hacia {x}.",
        "fr": "Nous poursuivons vers {x}.",
        "de": "Wir navigieren weiter zu {x}.",
        "pt": "Seguimos para {x}.",
        "ja": "{x} へ進みます。",
        "hi": "हम {x} की ओर आगे बढ़ते हैं।",
    },
    "Journey complete on {x}.": {
        "es": "Recorrido completo en {x}.",
        "fr": "Parcours terminé sur {x}.",
        "de": "Reise abgeschlossen auf {x}.",
        "pt": "Jornada concluída em {x}.",
        "ja": "{x} でジャーニー完了。",
        "hi": "{x} पर यात्रा पूर्ण।",
    },
    "We capture the state of {x}.": {
        "es": "Capturamos el estado de {x}.",
        "fr": "Nous capturons l'état de {x}.",
        "de": "Wir erfassen den Zustand von {x}.",
        "pt": "Capturamos o estado de {x}.",
        "ja": "{x} の状態をキャプチャします。",
        "hi": "हम {x} की स्थिति कैप्चर करते हैं।",
    },
    "Proof-gated walkthrough": {
        "es": "Recorrido con prueba de clics",
        "fr": "Parcours avec preuves de clic",
        "de": "Walkthrough mit Klick-Nachweis",
        "pt": "Walkthrough com prova de cliques",
        "ja": "証明付きウォークスルー",
        "hi": "प्रमाणित वॉकथ्रू",
    },
    "Thanks for watching": {
        "es": "Gracias por ver",
        "fr": "Merci d'avoir regardé",
        "de": "Danke fürs Zuschauen",
        "pt": "Obrigado por assistir",
        "ja": "ご視聴ありがとうございました",
        "hi": "देखने के लिए धन्यवाद",
    },
    "Generated by ShipVideo": {
        "es": "Generado por ShipVideo",
        "fr": "Généré par ShipVideo",
        "de": "Erstellt mit ShipVideo",
        "pt": "Gerado pelo ShipVideo",
        "ja": "ShipVideo で生成",
        "hi": "ShipVideo द्वारा जनरेट",
    },
    "Product journey": {
        "es": "Recorrido del producto",
        "fr": "Parcours produit",
        "de": "Produktreise",
        "pt": "Jornada do produto",
        "ja": "プロダクトジャーニー",
        "hi": "उत्पाद यात्रा",
    },
}


_PATTERNS = [
    (
        re.compile(r'^We open the starting link and land on (.+)\.$'),
        "We open the starting link and land on {x}.",
        ("x",),
    ),
    (
        re.compile(r'^We focus on [“"](.+?)[”"] — the next control to click\.$'),
        "We focus on “{x}” — the next control to click.",
        ("x",),
    ),
    (
        re.compile(r'^Next, we click [“"](.+?)[”"] and arrive at (.+)\.$'),
        "Next, we click “{x}” and arrive at {y}.",
        ("x", "y"),
    ),
    (
        re.compile(
            r'^We click [“"](.+?)[”"] and reach the end of the journey on (.+)\.$'
        ),
        "We click “{x}” and reach the end of the journey on {y}.",
        ("x", "y"),
    ),
    (
        re.compile(r'^We navigate to (.+) — end of the recorded path\.$'),
        "We navigate to {x} — end of the recorded path.",
        ("x",),
    ),
    (
        re.compile(r'^We navigate onward to (.+)\.$'),
        "We navigate onward to {x}.",
        ("x",),
    ),
    (
        re.compile(r'^Journey complete on (.+)\.$'),
        "Journey complete on {x}.",
        ("x",),
    ),
    (
        re.compile(r'^We capture the state of (.+)\.$'),
        "We capture the state of {x}.",
        ("x",),
    ),
]


def normalize_lang(lang: str) -> str:
    code = (lang or "en").strip().lower().replace("_", "-")
    if not code:
        return "en"
    base = code.split("-")[0]
    if base in SUPPORTED_LANGS:
        return base
    return "en"


def translate_phrase(text: str, lang: str) -> str:
    lang = normalize_lang(lang)
    if lang == "en" or not (text or "").strip():
        return text
    raw = text.strip()
    # Exact phrase table
    if raw in _PHRASES and lang in _PHRASES[raw]:
        return _PHRASES[raw][lang]
    for pat, key, keys in _PATTERNS:
        m = pat.match(raw)
        if not m:
            continue
        table = _PHRASES.get(key) or {}
        tpl = table.get(lang)
        if not tpl:
            return raw
        mapping = {k: m.group(i + 1) for i, k in enumerate(keys)}
        return tpl.format(**mapping)
    return raw


def translate_lines(lines: Sequence[str], lang: str) -> List[str]:
    lang = normalize_lang(lang)
    if lang == "en":
        return [str(x) for x in lines]
    out = [translate_phrase(str(x), lang) for x in lines]
    # If many lines unchanged, try optional LLM batch
    unchanged = sum(1 for a, b in zip(lines, out) if str(a).strip() == str(b).strip())
    if lines and unchanged / max(1, len(lines)) > 0.6:
        llm = _llm_translate_batch([str(x) for x in lines], lang)
        if llm and len(llm) == len(lines):
            return llm
    return out


def _llm_translate_batch(lines: List[str], lang: str) -> Optional[List[str]]:
    if os.getenv("SHIPVIDEO_I18N_LLM", "").strip().lower() in ("0", "false", "no"):
        return None
    try:
        from app.product.azure_subtitles import _chat_json  # type: ignore
    except Exception:
        try:
            return _azure_translate_fallback(lines, lang)
        except Exception:
            return None
    # Prefer a dedicated simple Azure call
    return _azure_translate_fallback(lines, lang)


def _azure_translate_fallback(lines: List[str], lang: str) -> Optional[List[str]]:
    endpoint = (os.getenv("AZURE_OPENAI_ENDPOINT") or "").rstrip("/")
    key = os.getenv("AZURE_OPENAI_API_KEY") or os.getenv("AZURE_OPENAI_KEY") or ""
    deployment = os.getenv("AZURE_OPENAI_DEPLOYMENT") or os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME") or ""
    api_version = os.getenv("AZURE_OPENAI_API_VERSION") or "2024-02-15-preview"
    if not (endpoint and key and deployment):
        return None
    try:
        import urllib.request

        url = f"{endpoint}/openai/deployments/{deployment}/chat/completions?api-version={api_version}"
        payload = {
            "messages": [
                {
                    "role": "system",
                    "content": (
                        f"Translate each demo narration line to language code '{lang}'. "
                        "Return JSON {\"lines\":[...]} with the same length and order. "
                        "Keep product names and UI labels in quotes unchanged when possible."
                    ),
                },
                {"role": "user", "content": json.dumps({"lines": lines}, ensure_ascii=False)},
            ],
            "temperature": 0.2,
            "response_format": {"type": "json_object"},
        }
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json", "api-key": key},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=45) as resp:
            body = json.loads(resp.read().decode("utf-8"))
        content = body["choices"][0]["message"]["content"]
        parsed = json.loads(content)
        out = parsed.get("lines")
        if isinstance(out, list) and len(out) == len(lines):
            return [str(x) for x in out]
    except Exception as e:
        logger.debug(
            "i18n llm translate failed",
            extra={"operation": "i18n_translate", "error": f"{type(e).__name__}: {e}"},
        )
    return None


def _srt_ts(seconds: float) -> str:
    if seconds < 0:
        seconds = 0.0
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = seconds % 60
    return f"{h:02d}:{m:02d}:{s:06.3f}".replace(".", ",")


def write_translated_srt(
    cues: Sequence[Dict[str, Any]],
    path: Path,
    lang: str,
) -> Path:
    lang = normalize_lang(lang)
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: List[str] = []
    for cue in cues:
        text = translate_phrase(str(cue.get("text") or ""), lang).replace("\n", " ").strip()
        lines.append(str(cue.get("index") or len(lines) + 1))
        lines.append(f"{_srt_ts(float(cue['start']))} --> {_srt_ts(float(cue['end']))}")
        lines.append(text)
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
